### PR TITLE
Porting to MCU

### PR DESCRIPTION
**Pull request by steveschnepp**
I'm planning to recreate a DYI hp48 device with a MCU, an OLED screen and some push buttons.

Here is the initial version of it for commenting

### CODE REVIEW

**Comment by gwenhael-le-moine** [comment]
I just wanted to drop a quick message to say that I love it.

Your work is fully aligned with what I would like to do and as I can't invest myself much I am very happy to welcome your contributions!

**Comment by steveschnepp** [comment]
Thanks!

I'll try to leave the core emulator intact and extract all I/O to external files for [drop-in portability](https://blog.pwkf.org/post/2009/12/Avoid-the-Preprocessor-Use-Compile-Time-Polymorphism-for-Cross-platform-Development).

Beware that I have some peculiar ways of working, heavy reworking the history being one, [1SOC](https://blog.pwkf.org/2023/08/17/one-sloc.html) being another :wink:

**Comment by gwenhael-le-moine** [comment]
Maybe of interest for you: I stumbled upon [drawille](https://github.com/asciimoo/drawille) ([C port](https://github.com/Huulivoide/libdrawille)) some time ago which I use for drawing a pseudo-LCD in the terminal in my [rpl.rb](https://github.com/gwenhael-le-moine/rpl.rb)

**Comment by steveschnepp** [comment]
Usage in https://github.com/gwenhael-le-moine/x48ng/blob/2994eca7426885605dec2bdd58b1d786dec93cdb/src/hp48_device_baremetal.c#L206

**Comment by steveschnepp** [comment]
@gwenhael-le-moine i'm really struggling to understand the segregation of the various files...

Then I looked at the original x48, and it made much more sense there. So I'll rebase my efforts onto the original codebase.

**Comment by gwenhael-le-moine** [comment]
Oh, ok. I look forward to see your take on x48, hope you publish it.

Your work here and reading your blog inspired me still, thank you for that.

**Comment by steveschnepp** [comment]
Thanks also for your work and appreciation.

The irony is that most of your work is great on the original fork, specially when you remove all the legacy cruft such as the prototypes.

But this last one takes it a little too far for me. :wink:
I'm a huge fan of many compilation units. The `-flto` flag from `gcc` automatically removes most of its overhead. Using a header-only approach with `static inline` covers the rest.

I'm still exploring[^1], but now I'll take a bottom-up approach, starting from scratch and re-adding functions of both repos when it makes sense, to avoid rewriting everything.

[^1]: So I might be totally wrong and backtrack. Which is a good thing for nice breakthroughs : learning from mistakes by calling them "failed experiments".

Targetting baremetal by design will (hopefully) make it easier to port it back to x11/sdl/...

And yes, I'll definitely publish it.

**Comment by steveschnepp** [comment]
I started at https://github.com/steveschnepp/mcu48
Not much to see yet, but copy/modify/paste is ongoing.

**Comment by gwenhael-le-moine** [comment]
Hi, I thought the version 0.27.0 might be of some interest as I just finalized a ncurses UI.

ui_text.c is quite simple and the dependency to ncurses light.

Also thank you to have nudged me to come back to x48ng with fresh motivation.

**Comment by steveschnepp** [comment]
Ncurse is indeed awesome

**Comment by steveschnepp** [comment]
on my side, i had several attempts with various back and forth on the strategy. So, congrats to actually finish a feature.

In the end the code is still very close to the original x48.

**Comment by steveschnepp** [comment]
so... once i finish the journey, i might try to port it to x48ng

**Pull request closed without merging**
